backend:
  - changed-files:
    - any-glob-to-any-file: ['unilog/**/*', 'api/**/*']

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/**/*', 'README.md', 'CHANGELOG.md']

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
